In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("data.csv")
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [3]:
# xtrain, xtest, ytrain, ytest = train_test_split(xdata, ydata, test_size = 0.3)

In [3]:
data['diagnosis'] = data['diagnosis'].map({'M' : 1, 'B' : 0}) # M : 1, B : 0 으로 변경
data.diagnosis

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [4]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [5]:
dataMean = data[['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean']]

In [6]:
dataMean
y = dataMean.loc[:, ['diagnosis']]

In [7]:
y=np.ravel(y) #1차원으로 변환, flatten와 같은 용도

In [8]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [73]:
# 2. 퀴즈
x = dataMean.iloc[:, 1:]

In [10]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [11]:
xTrain.shape

(455, 10)

In [12]:
xTest.shape
xTest

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
512        13.40         20.52           88.64      556.7          0.11060   
457        13.21         25.25           84.10      537.9          0.08791   
439        14.02         15.66           89.59      606.5          0.07966   
298        14.26         18.17           91.22      633.1          0.06576   
37         13.03         18.42           82.61      523.8          0.08983   
..           ...           ...             ...        ...              ...   
213        17.42         25.56          114.50      948.0          0.10060   
519        12.75         16.70           82.51      493.8          0.11250   
432        20.18         19.54          133.80     1250.0          0.11330   
516        18.31         20.58          120.80     1052.0          0.10680   
500        15.04         16.74           98.73      689.4          0.09883   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
512           0.14690         0.14450              0.08172         0.2116   
457           0.05205         0.02772              0.02068         0.1619   
439           0.05581         0.02087              0.02652         0.1589   
298           0.05220         0.02475              0.01374         0.1635   
37            0.03766         0.02562              0.02923         0.1467   
..                ...             ...                  ...            ...   
213           0.11460         0.16820              0.06597         0.1308   
519           0.11170         0.03880              0.02995         0.2120   
432           0.14890         0.21330              0.12590         0.1724   
516           0.12480         0.15690              0.09451         0.1860   
500           0.13640         0.07721              0.06142         0.1668   

     fractal_dimension_mean  
512                 0.07325  
457                 0.05584  
439                 0.05586  
298                 0.05586  
37                  0.05863  
..                      ...  
213                 0.05866  
519                 0.06623  
432                 0.06053  
516                 0.05941  
500                 0.06869  

[114 rows x 10 columns]

In [13]:
yTest

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [14]:
yTrain.shape

(455,)

In [15]:
yTest.shape

(114,)

In [ ]:
# xtrain, ytrain -> 모델 생성 -> xtest 입력 -> 예측값과 ytest(정답)을 출력

In [ ]:
# 모델.score(xTest, yTest)
# 1) 모델에 xTest가 입력
# 2) 모델에서는 예측 결과가 출력
# 3) 예측 결과와 yTest간 비교를 하여, 점수를 계산(100%)

In [17]:
dataMean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   diagnosis               569 non-null    int64  
 1   radius_mean             569 non-null    float64
 2   texture_mean            569 non-null    float64
 3   perimeter_mean          569 non-null    float64
 4   area_mean               569 non-null    float64
 5   smoothness_mean         569 non-null    float64
 6   compactness_mean        569 non-null    float64
 7   concavity_mean          569 non-null    float64
 8   concave points_mean     569 non-null    float64
 9   symmetry_mean           569 non-null    float64
 10  fractal_dimension_mean  569 non-null    float64
dtypes: float64(10), int64(1)
memory usage: 49.0 KB


In [18]:
from sklearn.metrics import make_scorer

In [19]:
def rmsle(pv, av) : # 예측값, 실제값
    # 넘파이 배열로 변환
    pv = np.array(pv)
    av = np.array(av)
    
    # 예측값과 실제값에 1을 더하고 로그를 씌운다
    log_predict = np.log(pv + 1)
    log_actual = np.log(av + 1)
    
    res = log_predict - log_actual
    res = np.square(res)
    
    mean_res = res.mean()
    score = np.sqrt(mean_res)
    return score

In [20]:
rmsle_scorer = make_scorer(rmsle)
rmsle_scorer

make_scorer(rmsle)

In [21]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [22]:
kfold = KFold(n_splits = 10, shuffle = True, random_state = 42)

In [23]:
from sklearn.ensemble import RandomForestRegressor

In [340]:
model = RandomForestRegressor(n_estimators = 200,
                              max_depth = 5,
                              min_samples_split = 4,
                              n_jobs = -1,
                              random_state = 42)

In [341]:
model.fit(xTrain, yTrain)

RandomForestRegressor(max_depth=5, min_samples_split=4, n_estimators=200,
                      n_jobs=-1, random_state=42)

In [342]:
pred = model.predict(xTest)
pred

array([9.42546002e-01, 7.68757766e-02, 4.80946841e-02, 5.50777759e-02,
       1.70099882e-02, 5.69053941e-04, 1.27006659e-01, 1.48202127e-03,
       1.71406081e-02, 1.80165052e-04, 2.36482681e-01, 1.60376179e-01,
       7.19691103e-02, 8.22347222e-01, 4.41196446e-01, 5.03047258e-01,
       2.08630853e-01, 9.95464099e-01, 9.97848715e-01, 9.97848715e-01,
       4.58387259e-01, 9.97848715e-01, 8.59615890e-02, 7.80406598e-04,
       9.46473903e-01, 3.08804392e-03, 1.30448504e-03, 9.76793082e-01,
       4.71632079e-03, 9.97848715e-01, 1.59434011e-03, 9.68721430e-01,
       1.05620303e-01, 9.96694868e-01, 1.09313238e-03, 7.69809847e-01,
       6.59434011e-03, 9.78628263e-01, 2.81071827e-03, 9.91165488e-01,
       7.43058741e-01, 1.80165052e-04, 8.41349947e-01, 1.09313238e-03,
       2.27890176e-02, 9.97848715e-01, 1.09313238e-03, 3.34219192e-02,
       1.09313238e-03, 9.78901984e-01, 9.33284585e-01, 9.38934421e-01,
       9.95102988e-01, 3.91559615e-03, 1.24113748e-02, 3.31535461e-03,
      

In [343]:
round(model.score(xTest, yTest)*100, 2)

83.12

In [166]:
score = cross_val_score(model, xTrain, yTrain, cv = kfold, scoring = rmsle_scorer)
score

array([0.0650412 , 0.19902361, 0.15697638, 0.11728359, 0.16355576,
       0.19573624, 0.13914525, 0.19518761, 0.17179086, 0.07159408])

In [167]:
score.mean()

0.14753345614635055

In [33]:
from sklearn.tree import DecisionTreeClassifier

In [77]:
model = DecisionTreeClassifier()
model.fit(xTrain, yTrain)

DecisionTreeClassifier()

In [59]:
round(model.score(xTest, yTest)*100, 2)

92.98

In [60]:
y_pred = model.predict(xTest)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1], dtype=int64)

In [61]:
yTest

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [348]:
from sklearn.ensemble import RandomForestClassifier

In [370]:
model = RandomForestClassifier(n_estimators = 100,
                              n_jobs = -1,
                              random_state = 42)

In [371]:
model.fit(xTrain, yTrain)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [372]:
pred_mean = model.predict(xTest)
pred_mean

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1], dtype=int64)

In [373]:
round(model.score(xTest, yTest)*100, 2)

94.74

In [264]:
data_whole = data.drop(['id', 'Unnamed: 32'], axis = 1)

In [265]:
y_whole = data_whole.loc[:, ['diagnosis']]

In [266]:
y_whole = np.ravel(y_whole)

In [267]:
x_whole = data_whole.iloc[:, 1:]

In [268]:
xTrain_whole, xTest_whole, yTrain_whole, yTest_whole = train_test_split(x_whole, y_whole, test_size = 0.2, random_state = 0)

In [269]:
model = DecisionTreeClassifier()
model.fit(xTrain_whole, yTrain_whole)

DecisionTreeClassifier()

In [270]:
round(model.score(xTest_whole, yTest_whole)*100, 2)

91.23

In [271]:
y_pred_whole = model.predict(xTest_whole)
y_pred_whole

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0], dtype=int64)

In [272]:
yTest_whole

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [344]:
model = RandomForestRegressor(n_estimators = 200,
                              max_depth = 5,
                              min_samples_split = 2,
                              n_jobs = -1,
                              random_state = 42)

In [345]:
model.fit(xTrain_whole, yTrain_whole)

RandomForestRegressor(max_depth=5, n_estimators=200, n_jobs=-1, random_state=42)

In [346]:
pred_whole = model.predict(xTest_whole)
pred_whole

array([0.99457368, 0.0612141 , 0.00208863, 0.11376699, 0.01304915,
       0.01345358, 0.00373215, 0.00330291, 0.00765026, 0.00306788,
       0.43469354, 0.02900721, 0.00208863, 0.77848987, 0.42110814,
       0.78265328, 0.06883678, 0.99785617, 0.99952284, 0.99952284,
       0.96479231, 0.99952284, 0.04494729, 0.00208863, 0.93880881,
       0.00708863, 0.00208863, 0.91920381, 0.00208863, 0.99952284,
       0.0070699 , 0.99077284, 0.03246984, 0.99761718, 0.00208863,
       0.9906278 , 0.00208863, 0.97465052, 0.01273237, 0.99702284,
       0.51598849, 0.03939638, 0.72843544, 0.00208863, 0.37472126,
       0.99952284, 0.00208863, 0.02625026, 0.00208863, 0.99952284,
       0.90962137, 0.94457492, 0.98961718, 0.00208863, 0.00208863,
       0.00208863, 0.08054743, 0.04269523, 0.08438077, 0.99952284,
       0.96556039, 0.99702284, 0.00208863, 0.00330291, 0.99455448,
       0.17652633, 0.99452284, 0.99952284, 0.99952284, 0.01165026,
       0.37788722, 0.99952284, 0.00208863, 0.27643651, 0.99952

In [347]:
round(model.score(xTest_whole, yTest_whole)*100, 2)

89.68

In [374]:
model = RandomForestClassifier(n_estimators = 100,
                              n_jobs = -1,
                              random_state = 42)

In [375]:
model.fit(xTrain_whole, yTrain_whole)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [377]:
y_pred_whole2 = model.predict(xTest_whole)
y_pred_whole2

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [378]:
round(model.score(xTest_whole, yTest_whole)*100, 2)

97.37

In [169]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [176]:
dataWorst = data[['diagnosis', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst']]

In [187]:
y_worst = dataWorst.loc[:, 'diagnosis']
y_worst = np.ravel(y_worst)

In [188]:
x_worst = dataWorst.iloc[:, 1:]

In [189]:
xTrain_worst, xTest_worst, yTrain_worst, yTest_worst = train_test_split(x_worst, y_worst, test_size = 0.2, random_state = 0)

In [190]:
model = DecisionTreeClassifier()
model.fit(xTrain_worst, yTrain_worst)

DecisionTreeClassifier()

In [191]:
round(model.score(xTest_worst, yTest_worst)*100, 2)

94.74

In [192]:
y_pred_worst = model.predict(xTest_worst)
y_pred_worst

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [193]:
yTest_worst

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [250]:
model = RandomForestRegressor(n_estimators = 200,
                              max_depth = 5,
                              min_samples_split = 2,
                              n_jobs = -1,
                              random_state = 42)

In [251]:
model.fit(xTrain_worst, yTrain_worst)

RandomForestRegressor(max_depth=5, n_estimators=200, n_jobs=-1, random_state=42)

In [252]:
pred_worst = model.predict(xTest_worst)
pred_worst

array([0.98086401, 0.05954583, 0.00286175, 0.02174506, 0.0495946 ,
       0.00286175, 0.0028386 , 0.00286175, 0.01514421, 0.00286175,
       0.14413699, 0.10495219, 0.00286175, 0.67806368, 0.19701336,
       0.87841263, 0.00960339, 0.99962387, 0.99962387, 0.99962387,
       0.98984126, 0.99962387, 0.02481801, 0.00286175, 0.99885464,
       0.00286175, 0.00286175, 0.88432071, 0.00286175, 0.99962387,
       0.09562637, 0.99629054, 0.03856768, 0.99203682, 0.00286175,
       0.98082889, 0.00286175, 0.98222416, 0.02685999, 0.99962387,
       0.41171369, 0.00286175, 0.67781588, 0.00286175, 0.42356716,
       0.99962387, 0.00286175, 0.04002301, 0.00286175, 0.99962387,
       0.98727625, 0.9053319 , 0.98453682, 0.00286175, 0.00286175,
       0.00286175, 0.08871249, 0.02454583, 0.08871249, 0.99962387,
       0.94225485, 0.99962387, 0.00286175, 0.00286175, 0.99962387,
       0.08454583, 0.99962387, 0.99962387, 0.99962387, 0.01235254,
       0.57031553, 0.99962387, 0.00286175, 0.22295187, 0.99829

In [253]:
round(model.score(xTest_worst, yTest_worst)*100, 2)

89.8

In [379]:
model = RandomForestClassifier(n_estimators = 100,
                              n_jobs = -1,
                              random_state = 42)

In [380]:
model.fit(xTrain_worst, yTrain_worst)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [381]:
y_pred_worst2 = model.predict(xTest_worst)
y_pred_worst2

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [382]:
round(model.score(xTest_worst, yTest_worst)*100, 2)

95.61

In [277]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [278]:
dataSe = data[['diagnosis', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se']]

In [279]:
y_se = dataSe.loc[:, 'diagnosis']
y_se = np.ravel(y_se)

In [280]:
x_se = dataSe.iloc[:, 1:]

In [281]:
xTrain_se, xTest_se, yTrain_se, yTest_se = train_test_split(x_se, y_se, test_size = 0.2, random_state = 0)

In [282]:
model = DecisionTreeClassifier()
model.fit(xTrain_se, yTrain_se)

DecisionTreeClassifier()

In [283]:
round(model.score(xTest_se, yTest_se)*100, 2)

85.96

In [284]:
y_pred_se = model.predict(xTest_se)
y_pred_se

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1], dtype=int64)

In [285]:
yTest_se

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [286]:
model = RandomForestRegressor(n_estimators = 200,
                              max_depth = 5,
                              min_samples_split = 2,
                              n_jobs = -1,
                              random_state = 42)

In [287]:
model.fit(xTrain_se, yTrain_se)

RandomForestRegressor(max_depth=5, n_estimators=200, n_jobs=-1, random_state=42)

In [288]:
pred_se = model.predict(xTest_se)
pred_se

array([0.66910682, 0.02957704, 0.31153814, 0.50457869, 0.01226893,
       0.02514732, 0.09393691, 0.00512789, 0.00933007, 0.05082928,
       0.88403079, 0.23655521, 0.04274412, 0.46987045, 0.86112362,
       0.97397247, 0.24146002, 0.99508734, 0.58336853, 0.98865013,
       0.83109352, 0.55618944, 0.01359634, 0.02644846, 0.86685306,
       0.25118853, 0.04262135, 0.10568939, 0.04946906, 0.99508734,
       0.28330111, 0.96731069, 0.51607463, 0.96176081, 0.00579164,
       0.69958163, 0.12696432, 0.98741057, 0.04493292, 0.99490877,
       0.87940302, 0.24184998, 0.52480624, 0.01346236, 0.51726406,
       0.98867421, 0.00533623, 0.14496731, 0.00512789, 0.5607283 ,
       0.62086545, 0.59037664, 0.99431189, 0.01755364, 0.2517977 ,
       0.01568687, 0.0360974 , 0.15447397, 0.04874451, 0.99508734,
       0.75983662, 0.99508734, 0.30774674, 0.0260433 , 0.87002325,
       0.50023079, 0.93470661, 0.93597087, 0.93680486, 0.00606826,
       0.64635331, 0.99508734, 0.05058662, 0.47928996, 0.99382

In [289]:
round(model.score(xTest_se, yTest_se)*100, 2)

66.35

In [290]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [311]:
dataMeanWorst = pd.concat([dataMean, dataWorst.drop('diagnosis', axis = 1)], axis = 1)

In [320]:
y_meanworst = dataMeanWorst.loc[:, 'diagnosis']
y_meanworst = np.ravel(y_meanworst)

In [322]:
x_meanworst = dataMeanWorst.iloc[:, 1:]

In [323]:
xTrain_meanworst, xTest_meanworst, yTrain_meanworst, yTest_meanworst = train_test_split(x_meanworst, y_meanworst, test_size = 0.2, random_state = 0)

In [326]:
model = DecisionTreeClassifier()
model.fit(xTrain_meanworst, yTrain_meanworst)

DecisionTreeClassifier()

In [327]:
round(model.score(xTest_meanworst, yTest_meanworst)*100, 2)

94.74

In [328]:
model = RandomForestRegressor(n_estimators = 200,
                              max_depth = 5,
                              min_samples_split = 2,
                              n_jobs = -1,
                              random_state = 42)

In [329]:
model.fit(xTrain_meanworst, yTrain_meanworst)

RandomForestRegressor(max_depth=5, n_estimators=200, n_jobs=-1, random_state=42)

In [330]:
pred_meanworst = model.predict(xTest_meanworst)
pred_meanworst

array([0.98982192, 0.05894959, 0.00346659, 0.05270853, 0.05904688,
       0.00278972, 0.00467921, 0.00776947, 0.01756984, 0.00278972,
       0.33354182, 0.0753438 , 0.00327379, 0.77498162, 0.30385035,
       0.81059815, 0.05745358, 0.99977107, 0.99977107, 0.99977107,
       0.93941574, 0.99977107, 0.03484259, 0.00278972, 0.92950347,
       0.00346659, 0.00278972, 0.89692228, 0.00278972, 0.99977107,
       0.07262651, 0.9908425 , 0.01635484, 0.99977107, 0.00278972,
       0.9856677 , 0.00278972, 0.9798044 , 0.01015542, 0.9983425 ,
       0.46170579, 0.00278972, 0.77375847, 0.00278972, 0.43006066,
       0.99977107, 0.00278972, 0.06316129, 0.00278972, 0.99977107,
       0.98483796, 0.94487346, 0.9933425 , 0.00278972, 0.00278972,
       0.00278972, 0.09275189, 0.01983522, 0.11560115, 0.99977107,
       0.97495635, 0.9983425 , 0.00278972, 0.00776947, 0.99977107,
       0.08858522, 0.99977107, 0.99977107, 0.99977107, 0.0236691 ,
       0.4046155 , 0.99977107, 0.00278972, 0.30746742, 0.99977

In [331]:
round(model.score(xTest_meanworst, yTest_meanworst)*100, 2)

90.34

In [399]:
model = RandomForestClassifier(n_estimators = 100,
                              n_jobs = -1,
                              random_state = 42)

In [400]:
model.fit(xTrain_meanworst, yTrain_meanworst)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [401]:
y_pred_meanworst2 = model.predict(xTest_meanworst)
y_pred_meanworst2

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0], dtype=int64)

In [402]:
round(model.score(xTest_meanworst, yTest_meanworst)*100, 2)

97.37