In [1]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [2]:
text=['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']
len(text)

11

In [3]:
vocab = {} # 파이썬의 dictionary 자료형
sentences = []
stop_words = set(stopwords.words('english'))

for i in text:
    sentence = word_tokenize(i) # 단어 토큰화를 수행합니다.
    result = []

    for word in sentence: 
        word = word.lower() # 모든 단어를 소문자화하여 단어의 개수를 줄입니다.
        if word not in stop_words: # 단어 토큰화 된 결과에 대해서 불용어를 제거합니다.
            if len(word) > 2: # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거합니다.
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0 #{person:2}
                vocab[word] += 1
    sentences.append(result) 
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [4]:
print(vocab)

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [5]:
#빈도수 기준으로 내림차순 정렬


sorted(vocab.items()) #키를 기준으로 오름차순

sorted(vocab.items(), reverse=True)#키를 기준으로 내림차순


vocab_sorted=sorted(vocab.items(), reverse=True, key=lambda x:x[1]) #key:정렬기준, x에는 튜플들이 전달됨

In [6]:
vocab_sorted

[('barber', 8),
 ('secret', 6),
 ('huge', 5),
 ('kept', 4),
 ('person', 3),
 ('word', 2),
 ('keeping', 2),
 ('good', 1),
 ('knew', 1),
 ('driving', 1),
 ('crazy', 1),
 ('went', 1),
 ('mountain', 1)]

In [7]:
word_to_index={}
i=0
for (word, freq) in vocab_sorted:
    if freq>1:
        i+=1
        word_to_index[word]=i
print(word_to_index)      


{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [8]:
#퀴즈1
#빈도수가 가장 높은 vs개 단어 추출
vs = 5

#인덱스가 5를 넘는 단어 제거
words_freq=[w for w,c in word_to_index.items() if c>vs]
words_freq

for w in words_freq:
    del word_to_index[w]

word_to_index['OOV']=len(word_to_index)+1
#vs개 만큼의 단어들만 추출 
print(word_to_index)


{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


In [9]:
sentences
#sentences(텍스트)의 단어 중에서 word_to_index(코퍼스, Vocabulary)에 없는 단어는 OOV라고 함

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [10]:
encoded=[]
for s in sentences:
    temp=[]
    for w in s:
        try:
            temp.append(word_to_index[w])
        except KeyError:
            temp.append(word_to_index['OOV'])
    encoded.append(temp)
print(encoded)     

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


In [11]:
from collections import Counter
import numpy as np

In [13]:
sentences

#퀴즈2.
#words=['barber', 'person','barber', 'good', 'person', ...,'barber', 'went', 'huge', 'mountain']
words = []
for s in sentences:
    for w in s:
            words.append(w)

# words
#words=np.hstack(sentences)
#words=sum(sentences, [])
words
vocab=Counter(words)
print(vocab['barber'])

8


In [14]:
vocab=vocab.most_common(vs) #빈도수가 가장 높은 5개 단어
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [15]:
i=0
word_to_index={}
for (w, f) in vocab:
    i+=1
    word_to_index[w]=i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
# 법령코퍼스={헌법:1, 피고인:2, ..., OOV:1000}
# OOV?자연어, 물, 컵,.., 경범죄

In [16]:
from nltk import FreqDist

In [17]:
vocab=FreqDist(np.hstack(sentences))
vocab
vocab['barber']

8

In [18]:
vocab=vocab.most_common(vs)

In [19]:
word_to_index={w[0]:i+1 for i, w in enumerate(vocab)}
word_to_index

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

In [66]:
###패딩:문장의 길이를 동일하게...

In [20]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [21]:
sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [22]:
tokenizer=Tokenizer()

In [23]:
tokenizer.fit_on_texts(sentences)

In [24]:
encoded=tokenizer.texts_to_sequences(sentences)
encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [25]:
max_len=max([len(i) for i in encoded]) #11
#가장 긴 길이를 출력 : 7

In [26]:
#왼쪽에 패딩, 오른쪽에 패딩
#[3,1,5,0,0,0,0]

encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [27]:
for item in encoded:
    while len(item)<max_len:
        item.append(0)
print(encoded)

[[1, 5, 0, 0, 0, 0, 0], [1, 8, 5, 0, 0, 0, 0], [1, 3, 5, 0, 0, 0, 0], [9, 2, 0, 0, 0, 0, 0], [2, 4, 3, 2, 0, 0, 0], [3, 2, 0, 0, 0, 0, 0], [1, 4, 6, 0, 0, 0, 0], [1, 4, 6, 0, 0, 0, 0], [1, 4, 2, 0, 0, 0, 0], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13, 0, 0, 0]]


In [28]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [29]:
encoded=tokenizer.texts_to_sequences(sentences)

In [30]:
pad_sequences(encoded)

pad_sequences(encoded, padding='post')

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [31]:
pad_sequences(encoded, padding='post', maxlen=5) #maxlen:문서의 최대 길이

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]])

In [32]:
pad_sequences(encoded, padding='post', maxlen=5, value=14) #maxlen:문서의 최대 길이

array([[ 1,  5, 14, 14, 14],
       [ 1,  8,  5, 14, 14],
       [ 1,  3,  5, 14, 14],
       [ 9,  2, 14, 14, 14],
       [ 2,  4,  3,  2, 14],
       [ 3,  2, 14, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  2, 14, 14],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14]])

In [89]:
#단어집합(자연어, 처리, 파이썬,...)->정수인코딩(1,2,3,...) -> 원핫인코딩(단어 집합의 크기를 벡터의 차원으로 간주)
#10차원 벡터(단어가 10개, 인덱스:1~10번까지)에서 해당 단어의 위치에는 1을 주고, 나머지에는 0을 주는 방식으로
#단어를 벡터 형태로 표현하게 됨.

# 자연어:1, 처리:2, 파이썬:3, ... 물:10
# 자연어 -> 1000000000
# 처리   -> 0100000000
# ...
# 물     -> 0000000001

In [33]:
from konlpy.tag import Okt

In [34]:
okt=Okt()
token=okt.morphs("나는 자연어 처리를 배운다")
print(token)

['나', '는', '자연어', '처리', '를', '배운다']


In [35]:
#{나:0, ... ,배운다:5}
word2index={}

for v in token:
    if v not in word2index.keys():
        word2index[v]=len(word2index)
print(word2index)    

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [36]:
word2index

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}

In [37]:
def ohe(word, word2index):
    #코딩
    ohv=[0]*len(word2index)
    idx=word2index[word]
    ohv[idx]=1    
    return ohv    

In [38]:
print(ohe("자연어", word2index)) #001000

[0, 0, 1, 0, 0, 0]


In [39]:
text="나랑 코엑스에 브로슈어 가지러 갈래 갈래 갈래 브로슈어 가지러 가자"

In [40]:
from tensorflow.keras.utils import to_categorical

In [41]:
tok=Tokenizer()
tok
tok.fit_on_texts([text])

In [42]:
tok.index_word
tok.word_index #단어집합

{'갈래': 1, '브로슈어': 2, '가지러': 3, '나랑': 4, '코엑스에': 5, '가자': 6}

In [43]:
text2="코엑스에 갈래 브로슈어 가지러 함께 가자 어서"

In [44]:
encoded=tok.texts_to_sequences([text2])[0] #정수 인코딩
encoded

[5, 1, 2, 3, 6]

In [45]:
oh=to_categorical(encoded)
oh

array([[0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [ ]:
#저장 효율이 떨어짐
#유사도? 구하기가 어려움

국어=[1000]
수학=[0100]
과학=[0010]
영어=[0001]
4차원 벡터
=> 검색어 : 제주도 숙박(숙식, 호텔, 모텔, 게스트하우스, 잠잘곳,...) 
    
문제 해결 방법? 단어에 의미를 부여하여 벡터화 (word2vec, fasttext, lsa, lda...)   

In [ ]:
##언어 모델? 단어의 순서에 확률을 적용한 모델
# - 통계적 기법 < 신경망 기법(LSTM, BERT,...)
# - 통계적 기법 : 이전 단어 등장시 다음 단어를 예측

#     코로나 검사 결과가 음성입니다 (BERT)

번역
P(나는 밥을 먹는다)  >>  P(나는 밥을 마신다)
손님~ 커피가
P(나왔습니다) >> P(나오셨습니다)
"손님~ 커피가 나왔습니다"

음성 인식 -> 자막 생성(나는 밥을 먹습니다 (50%))
나는 밥을 먹습니다 (50%)
나는 날을 먹습니다 (10%)
 ... 달을          (0.5%)



