In [1]:
import pandas as pd
from math import log
# 문장 -> tf(dtm) -> idf( log(n / (1 + df)) ) => tf * idf(element wise product)

In [3]:
docs = [
    '먹고 싶은 사과',
    '먹고 싶은 바나나',
    '길고 노란 바나나 바나나',
    '저는 과일이 좋아요'
]

In [8]:
list(set([w for doc in docs for w in doc.split()]))

['저는', '먹고', '좋아요', '사과', '노란', '길고', '싶은', '과일이', '바나나']

In [2]:
docs = [
    '먹고 싶은 사과',
    '먹고 싶은 바나나',
    '길고 노란 바나나 바나나',
    '저는 과일이 좋아요'
]
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()

In [9]:
N = len(docs)

def tf(t, d) :
    return d.count(t)

def idf(t) :
    df = 0
    for doc in docs :
        df += t in doc
    return log(N / (df + 1))

def tfidf(t, d) :
    return tf(t, d) * idf(t)

In [10]:
result = []
for i in range(N) :
    result.append([])
    d = docs[i]
    for j in range(len(vocab)) :
        t = vocab[j]
        result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = vocab)
tf_

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [11]:
result = []
for j in range(len(vocab)) :
    t = vocab[j]
    result.append(idf(t))
    
idf_ = pd.DataFrame(result, index = vocab, columns = ['idf'])
idf_

idf
과일이  0.693147
길고   0.693147
노란   0.693147
먹고   0.287682
바나나  0.287682
사과   0.693147
싶은   0.287682
저는   0.693147
좋아요  0.693147

In [12]:
result = []
for i in range(N) :
    result.append([])
    d = docs[i]
    for j in range(len(vocab)) :
        t = vocab[j]
        
        result[-1].append(tfidf(t, d))
        
tfidf_ = pd.DataFrame(result, columns = vocab)
tfidf_

과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

In [14]:
# 사이킷런 tfidf
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

In [15]:
vec = CountVectorizer()

In [18]:
print(vec.fit_transform(corpus).toarray()) # 코퍼스에서 단어의 빈도수를 추출
vec.vocabulary_

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]


{'you': 7,
 'know': 1,
 'want': 5,
 'your': 8,
 'love': 3,
 'like': 2,
 'what': 6,
 'should': 4,
 'do': 0}

In [ ]:
## 사이킷런의 tfidf 클래스를 사용하여 tfidf행렬을 구함

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
tv = TfidfVectorizer()

In [21]:
tfidfv = tv.fit(corpus)

In [22]:
print(tfidfv.transform(corpus).toarray())

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]


In [23]:
tfidfv.vocabulary_

{'you': 7,
 'know': 1,
 'want': 5,
 'your': 8,
 'love': 3,
 'like': 2,
 'what': 6,
 'should': 4,
 'do': 0}

In [33]:
tv = TfidfVectorizer(ngram_range = (1, 2))

In [34]:
tfidfv = tv.fit(corpus)

In [35]:
print(tfidfv.transform(corpus).toarray())

[[0.         0.34142622 0.34142622 0.         0.         0.34142622
  0.         0.         0.34142622 0.34142622 0.         0.
  0.25966344 0.34142622 0.34142622 0.34142622]
 [0.         0.         0.         0.62276601 0.62276601 0.
  0.         0.         0.         0.         0.         0.
  0.4736296  0.         0.         0.        ]
 [0.4472136  0.         0.         0.         0.         0.
  0.4472136  0.4472136  0.         0.         0.4472136  0.4472136
  0.         0.         0.         0.        ]]


In [36]:
tfidfv.vocabulary_

{'you': 12,
 'know': 1,
 'want': 8,
 'your': 14,
 'love': 5,
 'you know': 13,
 'know want': 2,
 'want your': 9,
 'your love': 15,
 'like': 3,
 'like you': 4,
 'what': 10,
 'should': 6,
 'do': 0,
 'what should': 11,
 'should do': 7}

In [38]:
import numpy as np
doc1 = np.array((2, 3, 0, 1))
doc2 = np.array((1, 2, 3, 1))
doc3 = np.array((2, 1, 2, 2))

In [39]:
docInput = np.array([1, 1, 0, 1])

In [51]:
# 퀴즈1.
# docInput 문서와 가장 가까운 문서를 출력(유클리디안 거리 공식)

def dist(x, y) :
    return sqrt(pow(x - y, 2).sum())
#     return (np.sqrt(np.sum((x - y)**2)))

print(dist(doc1, docInput))
print(dist(doc2, docInput))
print(dist(doc3, docInput))

2.23606797749979
3.1622776601683795
2.449489742783178


In [52]:
# 자카드 유사도 알고리즘
# 교집합 : 두 집합에서 공통으로 가지고 있는 원소 집합
# 합집합 : 두 집합에서 가지고 있는 원소 집합
# 합집합에서 교집합의 비율을 구하자. => 두 문서의 유사도

# J(doc1, doc2) = (doc1 교집합 doc2) / (doc1 합집합 doc2)
# 0 <= J(doc1, doc2) <= 1

# (doc1 합집합 doc2) = doc1 + doc2 - doc1교집합doc2


doc1 = "apple banana everyone like likey watch card holder"
doc2 = "apple banana coupon passport love you"

In [55]:
tok1 = doc1.split()
tok2 = doc2.split()

In [56]:
print(tok1)
print(tok2)

['apple', 'banana', 'everyone', 'like', 'likey', 'watch', 'card', 'holder']
['apple', 'banana', 'coupon', 'passport', 'love', 'you']


In [60]:
# 합집합
union = set(tok1).union(set(tok2))
union

{'apple',
 'banana',
 'card',
 'coupon',
 'everyone',
 'holder',
 'like',
 'likey',
 'love',
 'passport',
 'watch',
 'you'}

In [61]:
# 교집합
intersection = set(tok1).intersection(set(tok2))
intersection

{'apple', 'banana'}

In [64]:
# 자카드 유사도
print("자카드유사도 =", len(intersection) / len(union))

자카드유사도 = 0.16666666666666666


In [68]:
# 퀴즈2.
doc1 = np.array((2, 3, 0, 1))
doc2 = np.array((1, 2, 3, 1))
doc3 = np.array((2, 1, 2, 2))
docInput = np.array([1, 1, 0, 1])

# cos_sim(doc1, docInput)
# cos_sim(doc2, docInput)
# cos_sim(doc3, docInput)

def cos_sim(x, y) :
    return sum(x * y) / (sqrt(sum(x**2)) * sqrt(sum(y**2)))

print(cos_sim(doc1, docInput))
print(cos_sim(doc2, docInput))
print(cos_sim(doc3, docInput))

0.9258200997725515
0.5962847939999439
0.8006407690254358


In [71]:
from numpy import dot
from numpy.linalg import norm # 벡터 크기 계산 함수

def cos_sim(a, b) :
    return dot(a, b) / (norm(a) * norm(b))

print(cos_sim(doc1, docInput))
print(cos_sim(doc2, docInput))
print(cos_sim(doc3, docInput))

0.9258200997725515
0.5962847939999439
0.8006407690254358


In [ ]:
0 <= 피어슨 상관계수(x, y) = Covariance(x, y) / (std(x) * std(y)) <= 1

Covariance(x, y) = (Xi - Xu) * (Yi - Yu)

variance(x) = sum((Xi - Xu)**2) / n (모분산, 표준분산일 경우 n - 1)
std(x) = sqrt(variance(x))

In [72]:
# tfidf & cos sim => 영화 추천
import pandas as pd

In [73]:
data = pd.read_csv("movies_metadata.csv", low_memory = False)

In [75]:
data.shape
data.head()

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3  False                                                NaN  16000000   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   

                original_title  \
0                    Toy Story   
1                      Jumanji   
2             Grumpier Old Men   
3            Waiting to Exhale   
4  Father of the Bride Part II   

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2  A family wedding reignites the ancient feud be...  ...   1995-12-22   
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4  Just when George Banks has recovered from his ...  ...   1995-02-10   

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]   
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]   

     status                                            tagline  \
0  Released                                                NaN   
1  Released          Roll the dice and unleash the excitement!   
2  Released  Still Yelling. Still Fighting. Still Ready for...   
3  Released  Friends are the people who let you be yourself...   
4  Released  Just When His World Is Back To Normal... He's ...   

                         title  video vote_average vote_count  
0                    Toy Story  False          7.7     5415.0  
1                      Jumanji  False          6.9     2413.0  
2             Grumpier Old Men  False          6.5       92.0  
3            Waiting to Exhale  False          6.1       34.0  
4  Father of the Bride Part II  False          5.7      173.0  

[5 rows x 24 columns]

In [81]:
data = data.head(20000)

In [82]:
data.shape

(20000, 24)

In [86]:
data['overview']
# 전처리

data['overview'].isnull().sum() # ''
data['overview'] = data['overview'].fillna('')

In [87]:
data['overview'].isnull().sum()

0

In [88]:
# tfidf
tfidfMat = TfidfVectorizer(stop_words = 'english')
tfidfMat = tfidfMat.fit_transform(data['overview'])
tfidfMat.shape

(20000, 47487)

In [ ]:
# (20000, 47487)

In [109]:
print(np.max(tfidfMat[0].toarray()[0]))
tfidfMat[0].toarray().shape

# 퀴즈2. 
# 문제 : 0.5036643709879097에 해당되는 단어? index번호? 출럭
idx = tfidfMat[0].toarray().argmax()
vocab = TfidfVectorizer(stop_words = 'english').fit(data['overview']).vocabulary_
[key for key, value in vocab.items() if value == idx][0]

0.5036643709879097


'buzz'

In [ ]:
tfidfMat.shape

# tfidf 행렬
# 코사인유사도

In [110]:
from sklearn.metrics.pairwise import linear_kernel

In [130]:
cos_sim = linear_kernel(tfidfMat, tfidfMat)

In [112]:
cos_sim.shape

(20000, 20000)

In [113]:
cos_sim[0] # 모든 영화와의 코사인 유사도

array([1.        , 0.01575748, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [118]:
# print(data.index)
data['title']

indices = pd.Series(data.index, index = data['title']).drop_duplicates()
indices

title
Toy Story                                                                       0
Jumanji                                                                         1
Grumpier Old Men                                                                2
Waiting to Exhale                                                               3
Father of the Bride Part II                                                     4
                                                                            ...  
Rebellion                                                                   19995
Versailles                                                                  19996
Two in the Wave                                                             19997
Lotte Reiniger: Homage to the Inventor of the Silhouette Film               19998
RKO Production 601: The Making of 'Kong, the Eighth Wonder of the World'    19999
Length: 20000, dtype: int64

In [119]:
# indices['Jumanji']
# Jumanji 영화와 코사인 유사도가 가장 높은 20편의 영화제목을 출력(내림차순)
# ex)
# 12000 Kingkong
# 11000 Batman
# ...

1

In [145]:
sub = pd.DataFrame(cos_sim[1])
sub

0
0      0.015757
1      1.000000
2      0.049073
3      0.000000
4      0.000000
...         ...
19995  0.000000
19996  0.000000
19997  0.000000
19998  0.000000
19999  0.000000

[20000 rows x 1 columns]

In [156]:
sorted(sub[0], reverse = True)

[1.0000000000000004,
 0.18004489861497827,
 0.17893548282391925,
 0.17626361556882925,
 0.17184603122045175,
 0.15998391697583217,
 0.1597660946014838,
 0.15863282309276033,
 0.15508984041647625,
 0.1531015178499213,
 0.14983947719398977,
 0.14949215219226059,
 0.14901616822116737,
 0.14032952049014066,
 0.13969367969563323,
 0.13787293450956872,
 0.13202555571548596,
 0.13056314257666438,
 0.12950328472453557,
 0.1280982196435282,
 0.12771688493450198,
 0.1266531164767162,
 0.12326985579425767,
 0.12188350226583544,
 0.12052150508429182,
 0.11499153507806428,
 0.11498550502738639,
 0.11469404786776621,
 0.11397173030048435,
 0.11110078040178216,
 0.11050592961352627,
 0.11026151696648218,
 0.10944317806887387,
 0.10934760047172198,
 0.10915988800539349,
 0.1090558760408151,
 0.10816753938949152,
 0.10635491762952236,
 0.10560244278479104,
 0.1044289938500379,
 0.10332752575810424,
 0.10235844119144469,
 0.10090601098043293,
 0.10029879178668281,
 0.10025913556487029,
 0.09944237400513